apiVersion: v1alpha1
group: management
kind: JWTAuthRule
title: JWT AuthRule for Griffin Instruments v1
name: customjwtauth
metadata:
  scope:
    kind: Environment
    name: staging
spec:
    virtualAPIDefinition: griffininstrumentsv1
    policy: demoauth
