apiVersion: v1alpha1
group: management
kind: HttpBasicCredential
title: Musical Instruments Credentials (Basic Secret)
name: musicalinstrumentcredentialdefault
metadata:
    scope:
      kind: Environment
      name: staging
spec:
    description: Example HTTP basic credential using secret values.
    secret:
        name: musicalinstrumentsecret
---
apiVersion: v1alpha1
group: management
kind: APIKeyCredential
title: Musical Instruments Credentials (Bearer Secret)
name: musicalinstrumentcredentialoverride
metadata:
    scope:
      kind: Environment
      name: staging
spec:
    description: Example API Key credential using secret values.
    name: mykey
    in: header
    secret:
        name: musicalinstrumentsecret
    