apiVersion: v1alpha1
group: management
kind: RateLimitRule
title: Rate limit for Griffin Instruments v1
name: griffininstrumentsv1ratelimit
metadata:
    scope:
        kind: Environment
        name: staging
spec:
    virtualAPIDefinition: griffininstrumentsv1
    transactionPerSecond: 100