apiVersion: v1alpha1
group: management
kind: PathRoute
title: Route for Musical Instruments v1
name: griffininstrumentsv1route
metadata:
    scope:
      kind: Environment
      name: staging
spec:
    virtualAPIDefinition: griffininstrumentsv1
    cors: allowallcors
    auth: JWTAuthRule:customjwtauth
    prefix: /api/music
    route:
        apiServiceInstance: internal/musicalinstrumentsv1ars
        credential: HttpBasicCredential:musicalinstrumentcredentialdefault
        perPath:
            - path: /instruments/query
              cors: localhostcors
              credential: APIKeyCredential:musicalinstrumentcredentialoverride
