apiVersion: v1alpha1
group: management
kind: Secret
name: musicalinstrumentsecret
metadata:
    scope:
      kind: Environment
      name: staging
description: This is just for demostration purposes, it would be deployed out of band.
spec:
    data:
        username: fred
        password: flintstone
        token: secrettoken