apiVersion: v1alpha1
group: management
kind: Deployment
title: Griffin Musical Instruments v1 on Axway API Gateway
name: griffininstrumentsv1axway
metadata:
    scope:
      kind: Environment
      name: demostaging
spec:
    virtualAPIDefinition: griffininstrumentsv1
    stage: api-development