apiVersion: v1alpha1
group: management
scope: demostaging
kind: Secret
name: musicalinstrumentsecret
description: This is just for demostration purposes, it would be deployed out of band.
spec:
    data:
        username: fred
        password: flintstone
        token: secrettoken
---
apiVersion: v1alpha1
group: management
scope: demostaging
kind: HttpBasicCredential
title: Musical Instruments Credentials (Basic Secret)
name: musicalinstrumentcredentialdefault
spec:
    description: Example HTTP basic credential using secret values.
    secret:
        name: musicalinstrumentsecret
---
apiVersion: v1alpha1
group: management
scope: demostaging
kind: HttpBearerCredential
title: Musical Instruments Credentials (Bearer Secret)
name: musicalinstrumentcredentialoverride
spec:
    description: Example API Key credential using secret values.
    name: mykey
    in: header
    secret:
        name: musicalinstrumentsecret
    